name: Bug Report
description: File a bug report
title: "[Bug]: "
labels: ["bug", "triage"]
assignees: winstxnhdw
body:
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Also tell us, what did you expect to happen?
    validations:
      required: true

  - type: checkboxes
    id: duplicate-check
    attributes:
      label: Acknowledgement
      options:
        - label: I have done my due diligence to check for similar issues
          required: true
