name: Dependabot

on: pull_request

jobs:
  build:
    uses: winstxnhdw/actions/.github/workflows/bun.yml@main

  auto-merge:
    needs: build
    uses: winstxnhdw/actions/.github/workflows/dependabot-public.yml@main
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}
    permissions:
      contents: write
