name: Publish

on:
  workflow_run:
    workflows: CI
    branches: main
    types: completed
  push:
    branches: main
    paths:
      - .github/workflows/publish.yml
      - .changeset/**

concurrency: ${{ github.workflow }}-${{ github.ref }}

permissions:
  contents: write
  pull-requests: write

jobs:
  publish:
    if: github.event_name == 'push' || github.event.workflow_run.conclusion == 'success'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.1.1
        with:
          show-progress: false

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1.2.0
        with:
          bun-version: latest

      - name: Install node dependencies
        run: bun install --frozen-lockfile

      - name: Create release PR or publish
        uses: changesets/action@v1.4.6
        with:
          title: 'build: bump version packages'
          createGithubReleases: false
          publish: bun release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
