name: Publish

on:
  workflow_run:
    workflows: CI
    branches: main
    types: completed

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  publish:
    if: github.event.workflow_run.conclusion == 'success' || github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest

    permissions:
      contents: write
      pull-requests: write

    outputs:
      published: ${{ steps.changesets.outputs.published }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          show-progress: false

      - name: Setup Bun
        uses: oven-sh/setup-bun@735343b667d3e6f658f44d0eca948eb6282f2b76 # v2.0.2
        with:
          bun-version: latest

      - name: Install node dependencies
        run: bun install --frozen-lockfile

      - name: Create release PR or publish
        uses: changesets/action@001cd79f0a536e733315164543a727bdf2d70aff # v1.5.1
        id: changesets
        with:
          title: 'build: bump version packages'
          commit: 'build: bump version packages'
          publish: bun release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

  compile:
    runs-on: ${{ matrix.runs-on }}-latest
    strategy:
      matrix:
        runs-on: [ubuntu, macos, windows]

    steps:
      - name: Checkout repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
        with:
          show-progress: false

      - name: Setup Bun
        uses: oven-sh/setup-bun@735343b667d3e6f658f44d0eca948eb6282f2b76 # v2.0.2
        with:
          bun-version: latest

      - name: Install node dependencies
        run: bun install --frozen-lockfile

      - name: Compile
        run: bun compile

      - name: Test on Linux
        if: matrix.runs-on != 'windows'
        run: |
          bin/sgqr \
            --number +6591234567 \
            --amount 420.69 \
            --type image/svg+xml | cat | grep '<svg.*xmlns="http://www.w3.org/2000/svg"'

      - name: Test on Windows
        if: matrix.runs-on == 'windows'
        run: |
          bin/sgqr `
            --number +6591234567 `
            --amount 420.69 `
            --type image/svg+xml | Select-String "<svg.*xmlns=`"http://www.w3.org/2000/svg`""

      - name: Compress binary on Linux
        if: matrix.runs-on != 'windows'
        run: zip -rj sgqr-${{ matrix.runs-on }}.zip bin/sgqr

      - name: Compress binary on Windows
        if: matrix.runs-on == 'windows'
        run: Compress-Archive -Path bin/sgqr.exe -DestinationPath sgqr-${{ matrix.runs-on }}.zip

      - name: Upload artifact
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
        with:
          name: artifact-${{ matrix.runs-on }}
          path: sgqr-${{ matrix.runs-on }}.zip

  release:
    needs: [publish, compile]
    if: needs.publish.outputs.published == 'true'
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Download Linux artifact
        uses: actions/download-artifact@d3f86a106a0bac45b974a628896c90dbdf5c8093 # v4.3.0
        with:
          pattern: artifact-*
          merge-multiple: true

      - name: Rename artifacts
        run: |
          mv sgqr-ubuntu.zip sgqr-linux.zip
          mv sgqr-macos.zip sgqr-linux-arm64.zip

      - name: Release
        run: gh release upload $(gh release view --json tagName -q .tagName) sgqr-*.zip
        env:
          GH_TOKEN: ${{ github.token }}
          GH_REPO: ${{ github.repository }}
